https://www.machinelearningplus.com/python/101-pandas-exercises-python/

In [23]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Read Data

In [ ]:
# convert values
pd.read_csv('.csv', converters={'col': lambda x: })
# read specified columns
pd.read_csv('.csv', usecols=[col1, col2])

### Series

In [ ]:
# intersect, union
pd.Series(np.union1D(s1, s2))
pd.Series(np.intersect1d(s1, s2))

In [ ]:
# keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
s[~s.isin(s.value_counts().index[:2])] = 'Other'

# index of meeting conditions
np.argwhere(s.to_numpy() is True)

# flatten
np.array(s).flatten()



In [31]:
# e.g.
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1 == df.fruit2)
np.where(df.fruit1 == 'apple')
np.argwhere((df.fruit1 == df.fruit2).to_numpy())

(array([2, 6, 9]),)

(array([3, 5]),)

array([[2],
       [6],
       [9]])

### Indexing    

In [ ]:
df.col.idxmax()

# filtering by mask of index
mask = df.col.map(lambda x: x is True) # index of bool as mask
df.loc[mask, :]

# slice as series or dataframe
df[col] # series
df.loc[:, col] # series
df[[col]] # df
df.loc[:, [col]] # df

# stride
df.iloc[::5, :]
# reverse
df.iloc[::-1, :]

# one-hot
df_onehot = pd.concat([pd.get_dummies(df[col])], df[rest_of_col], axis=1)

### Describe function


In [ ]:
.describe()
.mean(axis=0)
.unique()
value_counts()

### Map and Apply

In [ ]:
# map is only for series
s.map(lambda)
df.col.map({1:'a', 2:'b'})

df.apply(lambda row: row.max() - row.min(), axis=)
df.col.apply(lambda)

# element-wise apply on df
df.applymap(lambda)

# apply with global variables
global_var = 'a'
df.apply(lambda x, global_va: x.fillna(global_var), args=(global_var,))

### Scaling and Normalization

Scaling: change the range of data, say [0, 100] -> [0,1]  
normalization: change the distribution to normal

In [ ]:
# scaling
from mlxtend.preprocessing import minmax_scaling
minmax_scaling(s)

# normalization
from scipy import stats
stats.boxcox(s)

# normalize all columns
df.apply(lambda x: ((x - x.mean())/x.std()).round(2))

### Group and Sort

Each group generated is a slice of df

In [ ]:

.groupby('a').b.count()
.groupby('col').apply(lambda df: )
.groupby([col1, col2]).col3.agg([len, min, max])

# reset index to remove multi-indexes
df_grouped.reset_index()

# sort by value
df.sort_values(by=[col1, col2], ascending=False)
# sort by index
df.sort_index(axis=, ascentding=False)

In [27]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
list(df_grouped.col2)
df_grouped.col2.agg([min])
df_grouped.get_group('apple')

[('apple',
  0    0.083407
  3    0.927535
  6    0.674664
  Name: col2, dtype: float64),
 ('banana',
  1    0.529740
  4    0.857285
  7    0.546951
  Name: col2, dtype: float64),
 ('orange',
  2    0.425301
  5    0.862884
  8    0.755118
  Name: col2, dtype: float64)]

min
col1            
apple   0.083407
banana  0.529740
orange  0.425301

col1      col2  col3
0  apple  0.083407     4
3  apple  0.927535    14
6  apple  0.674664    11

### Dtypes 

In [ ]:
df.col1.dtype
df.dtypes # columns consisting entirely of strings is object type
# how many columns under each dtype
df.dtypes.value_counts()


#### Date parsing

In [ ]:
from dateutil.parser import parse
s.map(lambda x: parse(x))
df['parsed'] = pd.to_datetime(df[date_col], format="%m/%d/%y", infer_datetime_format=True) # infer_datetime_format it's much slower than specifying the exact format of the dates.

# get the day of the month
df['parsed'].dt.day # dt.weekofyear, dayofyear, weekday_name

### Missing Values

Values are missing due to:
* it doesn't exist, then no need to fill it
* it wasn't recorded

In [ ]:
df[pd.isnull(df.col)] # pd.notnull()
# number of NaN
missing_each_col = df.apply(lambda x: x.isnull().sum())
missing_each_col.argmax() # col name with most missing

df.dropna(thresh=n_row*0.8, drop=True, axis=)


df.fillna()
# replace all NA's the value that comes directly after it in the same column, then replace all the remaining na's with 0. Good when data has logical order
df.fillna(method='bfill', axis=0).fillna(0)
# replace with mean
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# replace with mean
df.apply(lambda x: x.fillna(x.mean()))
# If missing value is denoted as NaN
df.replace(x, y)

### Duplicates and Unique

In [ ]:
df.nunique()
# get unique value
pd.unique(df.col)
# unique value and counts
df.col.value_counts()

In [37]:
# e.g.
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df.value_counts()
pd.value_counts(df.values.flatten())

a  b  c  d
1  1  7  3    1
2  8  1  6    1
      3  6    1
4  7  5  3    1
9  3  1  1    1
dtype: int64

1    5
3    4
2    2
8    2
6    2
7    2
4    1
5    1
9    1
dtype: int64

In [ ]:
# first : Mark duplicates as True except for the first occurrence.
# last : Mark duplicates as True except for the last occurrence.
# False : Mark all duplicates as True.
df.duplicated(subset=[col1], keep=) 

# number of duplicates
df.duplicated().sum()

# drop duplicates
df.drop_duplicates(subset=, )


### Renaming

In [ ]:
df.rename(columns={col1: col2})

# rename all index/columns with lanmda
df.rename_axis(lambda x: x*2, axis="index")
df.rename_axis(lambda x: x+"_renamed", axis="columns")

### Combining   

In [ ]:
df1.join(df2, on=, how=, lsuffix=, rsuffix=)

# e.g
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})
df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'pounds'], suffixes=['_left', '_right'])